### ISSUE TITLE
Running freezes game

### ISSUE THREAD

**Issue by beandipper** [NickMcConnell/FirstAgeAngband#40]
After making a few characters I've noticed that while trying to run in a direction, the game _sometimes_ 'freezes'. I can't seem to interact with the application then besides with 'Control-C' to commit suicide. It doesn't always happen when running.
Information about the setup:
-Using rogue like  keys
-Occurs with both Shift+Direction, as well as ','+Direction
-Compiled on Mac OS and ran in NCurses via the -mgcu flag on startup
-Compiled with flag to install locally instead of for entire system using `./configure --with-no-install`

I tried to dig around to see if I could find any log files that I could add here, but wasn't able to find anything. If anybody could let me know where I can find any debugging info, I would post it in here to help to reproduce the issue.

**Comment by NickMcConnell** [comment]
OK thanks, I'll watch out for that.

**Comment by beandipper** [comment]
Is there anywhere to check logs or the game output so that I can have more information? I would like to make sure this isn't an issue that isn't related the game.

**Comment by NickMcConnell** [comment]
Possibly fixed in 55a5cf5cf ?

**Comment by beandipper** [comment]
Thank you for taking a look at the issue. I pulled your changes and tested it, and the issue was still occurring.  However installing curses6 seemed to fix the problem.
I tried to recompile everything completely from a clean state which lead me to move from ncurses5 to ncurses6. I remember previously during configuration for compilation I followed the advice described here http://angband.oook.cz/forum/showthread.php?t=9155 for specifying a linked version of curses5w. That workaround seemed to allow for compilation but may have been the cause of the bug.
Compiling ncurses6, and then changing the configuration file to look for the newer version, and then recompiling seems to have done the trick. 

Taking a look at your changes, some of them may have been fixes that you wish to keep nonetheless
